### Default server port #########
server:
  port: 19000
mybatis:
  mapper-locations: classpath:/config/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml
  type-aliases-package: demo.springboot.model
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        fomate_sql: true
      show-sql: true